### PR TITLE
Smathot inline javascript

### PR DESCRIPTION
**Pull request by dschreij**
My additions of a proxied var_store (and coroutines class that accidentally slipped through).
I needed to change the inline_javascript class too, because the this.vars._prepare contents also were evaluated, and these tripped parser that is configured for osweb script. I don't think you'll want to store the inline js in the vars object, so I simply made _prepare and _run class properties. This works well for me, but can you give it a spin too?

### CODE REVIEW

**Comment by dschreij** [comment]
Commit c07b39b is the only one that is important of course...

**Comment by smathot** [comment]
I haven't been able to figure out why, but this breaks the feedback, or more specifically, the `correct` variable is no longer set. You can test this with for example the lexical-decision example. (I tested this after cherry-picking c07b39b).

**Comment by dschreij** [comment]
Strange, I notice this now too in the Posner cueing task. I'll look into it.

**Comment by dschreij** [comment]
I appear to have been a bit overzealous in refactoring the get() method of VarStore and broke variable retrieval from the global varstore because of that. It's strange that the unit tests didn't pick this up as the VarStore is used extensively in the tests of Syntax, but I think this is because all VarStores there are local, and never try to retrieve a variable from their parent store. This situation of course needs to be addressed with some extra tests, so I will add them when time permits.
As for now, the proxy is in place for VarStore and everything appears to work correctly for me again. Please let me know if you find other funny stuff...

**Comment by smathot** [comment]
The `VarStore` proxy does work as expected now, in the sense that it behaves as it should in the `inline_javascript` item. However, the code of OSWeb itself assumes that retrieving variables as attributes does *not* result in evaluation. Hence, the changed behavior of the `VarStore` breaks things. I noticed this in an experiment that used a break-if statement in a `loop`, but I imagine analogous will crop up elsewhere.

So I suggest that we leave the `VarStore` as it was for OSWeb itself, and only expose the Proxy to the `inline_javascript` workspace. Do you agree?

**Comment by dschreij** [comment]
Of course, it will evaluate the already evaluated string again. That's a pity. Go ahead and make the change you suggested (or disregard this pull request ;) )

I do find it strange though that this breaks things, because if a string doesn't contain variables, it should just return the string as is. So re-evaluating an evaluated string should just return the same result?

**Comment by smathot** [comment]
> So re-evaluating an evaluated string should just return the same result?

Yes, but what happens for example in the case of the break-if statement is that it is first accessed as a property during the prepare phase, but it shouldn't be evaluated yet then. And then later it is explicitly evaluated. So the time point of evaluation changes, so to say.

In a sense of course this is because of messy coding to begin with. But that's a given now, so we cannot change the behavior of the `VarStore` without expecting side effects. So yes, I'll close this pull request and add a proxy based on this, but then only to the workspace!

**Pull request closed without merging**
